/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAcademicYearsRouteImport } from './routes/_authenticated/academic-years'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedAcademicYearsCreateRouteImport } from './routes/_authenticated/academic-years.create'
import { Route as AuthenticatedAllusersIndexRouteImport } from './routes/_authenticated/allusers/index'
import { Route as AuthenticatedAllusersUserIdRouteImport } from './routes/_authenticated/allusers/$userId'
import { Route as AuthenticatedExamsCreateRouteImport } from './routes/_authenticated/exams.create'
import { Route as AuthenticatedExamsPublishRouteImport } from './routes/_authenticated/exams.publish'
import { Route as AuthenticatedFieldofstudyIndexRouteImport } from './routes/_authenticated/fieldofstudy/index'
import { Route as AuthenticatedFieldofstudyFieldofstudyIdRouteImport } from './routes/_authenticated/fieldofstudy/$fieldofstudyId'
import { Route as AuthenticatedSchoolsIndexRouteImport } from './routes/_authenticated/schools/index'
import { Route as AuthenticatedSchoolsSchoolIdRouteImport } from './routes/_authenticated/schools/$schoolId'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students/$studentId'
import { Route as AuthenticatedStudentsImportRouteImport } from './routes/_authenticated/students/import'
import { Route as AuthenticatedStudentsRankingsRouteImport } from './routes/_authenticated/students/rankings'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademicYearsRoute =
  AuthenticatedAcademicYearsRouteImport.update({
    id: '/academic-years',
    path: '/academic-years',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademicYearsCreateRoute =
  AuthenticatedAcademicYearsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedAcademicYearsRoute,
  } as any)
const AuthenticatedAllusersIndexRoute =
  AuthenticatedAllusersIndexRouteImport.update({
    id: '/allusers/',
    path: '/allusers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAllusersUserIdRoute =
  AuthenticatedAllusersUserIdRouteImport.update({
    id: '/allusers/$userId',
    path: '/allusers/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamsCreateRoute =
  AuthenticatedExamsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedExamsPublishRoute =
  AuthenticatedExamsPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedFieldofstudyIndexRoute =
  AuthenticatedFieldofstudyIndexRouteImport.update({
    id: '/fieldofstudy/',
    path: '/fieldofstudy/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFieldofstudyFieldofstudyIdRoute =
  AuthenticatedFieldofstudyFieldofstudyIdRouteImport.update({
    id: '/fieldofstudy/$fieldofstudyId',
    path: '/fieldofstudy/$fieldofstudyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsIndexRoute =
  AuthenticatedSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsSchoolIdRoute =
  AuthenticatedSchoolsSchoolIdRouteImport.update({
    id: '/schools/$schoolId',
    path: '/schools/$schoolId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsImportRoute =
  AuthenticatedStudentsImportRouteImport.update({
    id: '/students/import',
    path: '/students/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsRankingsRoute =
  AuthenticatedStudentsRankingsRouteImport.update({
    id: '/students/rankings',
    path: '/students/rankings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/academic-years': typeof AuthenticatedAcademicYearsRouteWithChildren
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/test': typeof AuthenticatedTestRoute
  '/academic-years/create': typeof AuthenticatedAcademicYearsCreateRoute
  '/allusers/$userId': typeof AuthenticatedAllusersUserIdRoute
  '/exams/create': typeof AuthenticatedExamsCreateRoute
  '/exams/publish': typeof AuthenticatedExamsPublishRoute
  '/fieldofstudy/$fieldofstudyId': typeof AuthenticatedFieldofstudyFieldofstudyIdRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/students/rankings': typeof AuthenticatedStudentsRankingsRoute
  '/allusers/': typeof AuthenticatedAllusersIndexRoute
  '/fieldofstudy/': typeof AuthenticatedFieldofstudyIndexRoute
  '/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/academic-years': typeof AuthenticatedAcademicYearsRouteWithChildren
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/test': typeof AuthenticatedTestRoute
  '/': typeof AuthenticatedIndexRoute
  '/academic-years/create': typeof AuthenticatedAcademicYearsCreateRoute
  '/allusers/$userId': typeof AuthenticatedAllusersUserIdRoute
  '/exams/create': typeof AuthenticatedExamsCreateRoute
  '/exams/publish': typeof AuthenticatedExamsPublishRoute
  '/fieldofstudy/$fieldofstudyId': typeof AuthenticatedFieldofstudyFieldofstudyIdRoute
  '/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/students/import': typeof AuthenticatedStudentsImportRoute
  '/students/rankings': typeof AuthenticatedStudentsRankingsRoute
  '/allusers': typeof AuthenticatedAllusersIndexRoute
  '/fieldofstudy': typeof AuthenticatedFieldofstudyIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/academic-years': typeof AuthenticatedAcademicYearsRouteWithChildren
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRouteWithChildren
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/academic-years/create': typeof AuthenticatedAcademicYearsCreateRoute
  '/_authenticated/allusers/$userId': typeof AuthenticatedAllusersUserIdRoute
  '/_authenticated/exams/create': typeof AuthenticatedExamsCreateRoute
  '/_authenticated/exams/publish': typeof AuthenticatedExamsPublishRoute
  '/_authenticated/fieldofstudy/$fieldofstudyId': typeof AuthenticatedFieldofstudyFieldofstudyIdRoute
  '/_authenticated/schools/$schoolId': typeof AuthenticatedSchoolsSchoolIdRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/students/import': typeof AuthenticatedStudentsImportRoute
  '/_authenticated/students/rankings': typeof AuthenticatedStudentsRankingsRoute
  '/_authenticated/allusers/': typeof AuthenticatedAllusersIndexRoute
  '/_authenticated/fieldofstudy/': typeof AuthenticatedFieldofstudyIndexRoute
  '/_authenticated/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/set-password'
    | '/academic-years'
    | '/attendance'
    | '/exams'
    | '/help'
    | '/permissions'
    | '/roles'
    | '/test'
    | '/academic-years/create'
    | '/allusers/$userId'
    | '/exams/create'
    | '/exams/publish'
    | '/fieldofstudy/$fieldofstudyId'
    | '/schools/$schoolId'
    | '/students/$studentId'
    | '/students/import'
    | '/students/rankings'
    | '/allusers/'
    | '/fieldofstudy/'
    | '/schools/'
    | '/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/set-password'
    | '/academic-years'
    | '/attendance'
    | '/exams'
    | '/help'
    | '/permissions'
    | '/roles'
    | '/test'
    | '/'
    | '/academic-years/create'
    | '/allusers/$userId'
    | '/exams/create'
    | '/exams/publish'
    | '/fieldofstudy/$fieldofstudyId'
    | '/schools/$schoolId'
    | '/students/$studentId'
    | '/students/import'
    | '/students/rankings'
    | '/allusers'
    | '/fieldofstudy'
    | '/schools'
    | '/students'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/set-password'
    | '/_authenticated/academic-years'
    | '/_authenticated/attendance'
    | '/_authenticated/exams'
    | '/_authenticated/help'
    | '/_authenticated/permissions'
    | '/_authenticated/roles'
    | '/_authenticated/test'
    | '/_authenticated/'
    | '/_authenticated/academic-years/create'
    | '/_authenticated/allusers/$userId'
    | '/_authenticated/exams/create'
    | '/_authenticated/exams/publish'
    | '/_authenticated/fieldofstudy/$fieldofstudyId'
    | '/_authenticated/schools/$schoolId'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/students/import'
    | '/_authenticated/students/rankings'
    | '/_authenticated/allusers/'
    | '/_authenticated/fieldofstudy/'
    | '/_authenticated/schools/'
    | '/_authenticated/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-years': {
      id: '/_authenticated/academic-years'
      path: '/academic-years'
      fullPath: '/academic-years'
      preLoaderRoute: typeof AuthenticatedAcademicYearsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-years/create': {
      id: '/_authenticated/academic-years/create'
      path: '/create'
      fullPath: '/academic-years/create'
      preLoaderRoute: typeof AuthenticatedAcademicYearsCreateRouteImport
      parentRoute: typeof AuthenticatedAcademicYearsRoute
    }
    '/_authenticated/allusers/': {
      id: '/_authenticated/allusers/'
      path: '/allusers'
      fullPath: '/allusers/'
      preLoaderRoute: typeof AuthenticatedAllusersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/allusers/$userId': {
      id: '/_authenticated/allusers/$userId'
      path: '/allusers/$userId'
      fullPath: '/allusers/$userId'
      preLoaderRoute: typeof AuthenticatedAllusersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams/create': {
      id: '/_authenticated/exams/create'
      path: '/create'
      fullPath: '/exams/create'
      preLoaderRoute: typeof AuthenticatedExamsCreateRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/exams/publish': {
      id: '/_authenticated/exams/publish'
      path: '/publish'
      fullPath: '/exams/publish'
      preLoaderRoute: typeof AuthenticatedExamsPublishRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/fieldofstudy/': {
      id: '/_authenticated/fieldofstudy/'
      path: '/fieldofstudy'
      fullPath: '/fieldofstudy/'
      preLoaderRoute: typeof AuthenticatedFieldofstudyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fieldofstudy/$fieldofstudyId': {
      id: '/_authenticated/fieldofstudy/$fieldofstudyId'
      path: '/fieldofstudy/$fieldofstudyId'
      fullPath: '/fieldofstudy/$fieldofstudyId'
      preLoaderRoute: typeof AuthenticatedFieldofstudyFieldofstudyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/': {
      id: '/_authenticated/schools/'
      path: '/schools'
      fullPath: '/schools/'
      preLoaderRoute: typeof AuthenticatedSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/$schoolId': {
      id: '/_authenticated/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/schools/$schoolId'
      preLoaderRoute: typeof AuthenticatedSchoolsSchoolIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/import': {
      id: '/_authenticated/students/import'
      path: '/students/import'
      fullPath: '/students/import'
      preLoaderRoute: typeof AuthenticatedStudentsImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/rankings': {
      id: '/_authenticated/students/rankings'
      path: '/students/rankings'
      fullPath: '/students/rankings'
      preLoaderRoute: typeof AuthenticatedStudentsRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAcademicYearsRouteChildren {
  AuthenticatedAcademicYearsCreateRoute: typeof AuthenticatedAcademicYearsCreateRoute
}

const AuthenticatedAcademicYearsRouteChildren: AuthenticatedAcademicYearsRouteChildren =
  {
    AuthenticatedAcademicYearsCreateRoute:
      AuthenticatedAcademicYearsCreateRoute,
  }

const AuthenticatedAcademicYearsRouteWithChildren =
  AuthenticatedAcademicYearsRoute._addFileChildren(
    AuthenticatedAcademicYearsRouteChildren,
  )

interface AuthenticatedExamsRouteChildren {
  AuthenticatedExamsCreateRoute: typeof AuthenticatedExamsCreateRoute
  AuthenticatedExamsPublishRoute: typeof AuthenticatedExamsPublishRoute
}

const AuthenticatedExamsRouteChildren: AuthenticatedExamsRouteChildren = {
  AuthenticatedExamsCreateRoute: AuthenticatedExamsCreateRoute,
  AuthenticatedExamsPublishRoute: AuthenticatedExamsPublishRoute,
}

const AuthenticatedExamsRouteWithChildren =
  AuthenticatedExamsRoute._addFileChildren(AuthenticatedExamsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademicYearsRoute: typeof AuthenticatedAcademicYearsRouteWithChildren
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRouteWithChildren
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAllusersUserIdRoute: typeof AuthenticatedAllusersUserIdRoute
  AuthenticatedFieldofstudyFieldofstudyIdRoute: typeof AuthenticatedFieldofstudyFieldofstudyIdRoute
  AuthenticatedSchoolsSchoolIdRoute: typeof AuthenticatedSchoolsSchoolIdRoute
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
  AuthenticatedStudentsImportRoute: typeof AuthenticatedStudentsImportRoute
  AuthenticatedStudentsRankingsRoute: typeof AuthenticatedStudentsRankingsRoute
  AuthenticatedAllusersIndexRoute: typeof AuthenticatedAllusersIndexRoute
  AuthenticatedFieldofstudyIndexRoute: typeof AuthenticatedFieldofstudyIndexRoute
  AuthenticatedSchoolsIndexRoute: typeof AuthenticatedSchoolsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademicYearsRoute: AuthenticatedAcademicYearsRouteWithChildren,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRouteWithChildren,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAllusersUserIdRoute: AuthenticatedAllusersUserIdRoute,
  AuthenticatedFieldofstudyFieldofstudyIdRoute:
    AuthenticatedFieldofstudyFieldofstudyIdRoute,
  AuthenticatedSchoolsSchoolIdRoute: AuthenticatedSchoolsSchoolIdRoute,
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
  AuthenticatedStudentsImportRoute: AuthenticatedStudentsImportRoute,
  AuthenticatedStudentsRankingsRoute: AuthenticatedStudentsRankingsRoute,
  AuthenticatedAllusersIndexRoute: AuthenticatedAllusersIndexRoute,
  AuthenticatedFieldofstudyIndexRoute: AuthenticatedFieldofstudyIndexRoute,
  AuthenticatedSchoolsIndexRoute: AuthenticatedSchoolsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
